<a href="https://colab.research.google.com/github/youngsu1jeong/202007_bootcamp1/blob/master/g_28_%E1%84%89%E1%85%B5%E1%84%80%E1%85%A8%E1%84%8B%E1%85%A7%E1%86%AFMLP_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sequence Analysis
- Forecasting (예측, Regression)
- Pattern Classification

## 런타임 유형 GPU, 크롬으로 접속

## 예측
### 선형모델과 딥러닝모델 비교

In [ ]:
import numpy as np
from numpy import array
from sklearn.linear_model import LinearRegression
%tensorflow_version 2.x
from keras import Sequential
from keras.layers import Dense
import warnings
warnings.simplefilter('ignore')


TensorFlow is already loaded. Please restart the runtime to change versions.


### 입력 및 예측 데이터 생성 (X, y)

In [ ]:
def split_data(data, n_steps):
    x, y = [], []
    for i in range(len(data)):
        if i > len(data) - n_steps - 1 : break
        x.append(data[i:i+n_steps])
        y.append(data[i+n_steps])
    return np.array(x), np.array(y)

In [ ]:
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
n_steps=3
X, y = split_data(data, n_steps)
for i in range(len(X)):
  print(X[i], y[i])

[1 2 3] 4
[2 3 4] 5
[3 4 5] 6
[4 5 6] 7
[5 6 7] 8
[6 7 8] 9
[7 8 9] 10


### 선형모델 (Linear Prediction)

In [ ]:
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
n_steps=3
X, y = split_data(data, n_steps)
lr = LinearRegression()
lr.fit(X, y) 

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
x_input = array([7, 8, 9])
x_input = x_input.reshape(-1, n_steps)
lr.predict(x_input)

array([10.])

In [ ]:
x_input = array([[0.7, 0.8, 0.9],[70, 80, 90],[700, 800, 900]])
x_input = x_input.reshape(-1, n_steps)
lr.predict(x_input)

array([  2.8,  82. , 802. ])

In [ ]:
lr.coef_, lr.intercept_

(array([0.33333333, 0.33333333, 0.33333333]), 2.0)

## MLP 모델 사용
- Multi Layer Perceptron

In [ ]:
n_steps = 3
X, y = split_data(data, n_steps)
for i in range(len(X)):
  print(X[i], y[i])

[1 2 3] 4
[2 3 4] 5
[3 4 5] 6
[4 5 6] 7
[5 6 7] 8
[6 7 8] 9
[7 8 9] 10


In [ ]:
model = Sequential()
model.add(Dense(100, activation='relu', input_dim=n_steps)) 
model.add(Dense(100)) 
model.add(Dense(100)) 
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [ ]:
model.fit(X, y, epochs=1000, verbose=0)

In [ ]:
x_input = array([[0.7, 0.8, 0.9],[7, 8, 9],[70, 80, 90],[700, 800, 900]])
x_input = x_input.reshape((-1, n_steps))
model.predict(x_input, verbose=0)

array([[  1.4683497],
       [  9.999862 ],
       [ 95.67914  ],
       [952.67615  ]], dtype=float32)